#!/bin/bash -l
#SBATCH -p small            
#SBATCH -N 1                # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:20:00         # adjust the amount of time as necessary
#SBATCH -J auto-openmp
#SBATCH -o auto-openmp.%j.stdout
#SBATCH -e auto-openmp.%j.error

rm openmp.txt
./serial -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=1
./openmp -p 1 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -p 2 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=8
./openmp -p 8 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=11
./openmp -p 11 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=22
./openmp -p 22 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=33
./openmp -p 33 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=44
./openmp -p 44 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -p 2 -n 1000 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 2000 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 3000 -no -s openmp.txt
export OMP_NUM_THREADS=8
./openmp -p 8 -n 4000 -no -s openmp.txt
export OMP_NUM_THREADS=16
./openmp -p 16 -n 8000 -no -s openmp.txt
export OMP_NUM_THREADS=32
./openmp -p 32 -n 16000 -no -s openmp.txt
export OMP_NUM_THREADS=44
./openmp -p 44 -n 22000 -no -s openmp.txt
./autograder -v openmp -s openmp.txt
